name: catholic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  json_annotation: ^4.3.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0
  build_runner: ^2.1.1

flutter:
  uses-material-design: true

